baseURL = 'https://williansfaria.com'
languageCode = 'en-us'
title = 'Willians Faria'
theme = "diary"
DefaultContentLanguage = "en"
googleAnalytics = "G-NCJJ4TMY34"

[params]
favicon = "/favicon.ico"
enableReadingTime=true

[[menu.main]]
url = "/posts"
name = "Blog"
weight = 1

[[menu.main]]
url = "/bytes"
name = "Bytes"
weight = 2

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github-dark"
    tabWidth = 4
